Repository borbely-dominik-peter/Proj1-TelefonosUgyfelszolgalat-10A_G, pull requests merged in 2023-02, with the labels that each got.

#6 alap
  .vscode/launch.json
  main.py
Labels: good first issue

#12 1 és második feladat
  .vscode/launch.json
  Megoldas.py
  __pycache__/Megoldas.cpython-310.pyc
  __pycache__/phone_numbers.cpython-310.pyc
  main.py
  phone_numbers.py
Labels: documentation

#15 3. feladat
  main.py
Labels: documentation

#16 Update README.md
  README.md
Labels: Task

#22 20 5 feladat várakozó száma
  Megoldas.py
  __pycache__/Megoldas.cpython-310.pyc
  __pycache__/phone_numbers.cpython-310.pyc
  hivastest.txt
  main.py
Labels: Task

#27 25 6 feladat javítás
  Call.py
  Megoldas.py
  __pycache__/Call.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  __pycache__/phone_numbers.cpython-310.pyc
  main.py
  phone_numbers.py
Labels: File Bug
